version: '3.9'

services:
  casher_db:
    container_name: casher_db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_root
      POSTGRES_PASSWORD: dev_root
      POSTGRES_DB: casher_db
    volumes:
      - pg_data

  es01:
    image: elasticsearch:8.4.3
    container_name: es01
    environment:
      - ELASTIC_PASSWORD=admin
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
   pg_data:
   data01:
     driver: local
