version: '3.9'

services:
  casher_core:
    container_name: casher_core
    image: casher_core
    env_file:
      - .env
    ports:
      - 3000:3000
  casher_db:
    container_name: casher_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev_root
      POSTGRES_PASSWORD: dev_root
      POSTGRES_DB: casher_db
    volumes:
      - local_data:/var/lib/postgesql/data

volumes:
  local_data:
