version: '3.9'

services:
  casher_db:
    container_name: casher_db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_root
      POSTGRES_PASSWORD: dev_root
      POSTGRES_DB: casher_db
    volumes:
      - pg_data:/var/lib/postgesql/data
  file_storage:
    container_name: mino
    image: quay.io/minio/minio
    volumes:
      - ./.data/mino:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    command: 'server /data --console-address ":9090"'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  casher_es01:
    image: elasticsearch:8.4.3
    container_name: casher_es01
    environment:
      - ELASTIC_PASSWORD=admin
      - node.name=casher_es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  casher_kibana:
    container_name: casher_kibana
    depends_on:
      - casher_es01
    image: kibana:8.4.3
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://casher_es01:9200
      - ELASTICSEARCH_USERNAME=elastic/kibana
      - ELASTICSEARCH_PASSWORD=admin



volumes:
  pg_data:
  data01:
  kibana_data:
  file_data:
    driver: local

